# Class 9
## Date: 23/03/2026

## **Indexing and Slicing**

#### **1-D ARRAY**

In [6]:
import numpy as np

In [7]:
product_list = ['fruit', 'vegeteable', 'cereal', 'dairy', 'eggs', 'snacks', 'beverages', 'coffee', 'tea', 'spices']
product_array = np.array(product_list)

In [8]:
product_list

['fruit',
 'vegeteable',
 'cereal',
 'dairy',
 'eggs',
 'snacks',
 'beverages',
 'coffee',
 'tea',
 'spices']

In [9]:
product_array

array(['fruit', 'vegeteable', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [10]:
product_array.size

10

In [11]:
len(product_array)

10

In [12]:
product_array[-1]

np.str_('spices')

In [13]:
product_list[1]

'vegeteable'

In [14]:
product_array[2:6]

array(['cereal', 'dairy', 'eggs', 'snacks'], dtype='<U10')

#### **2-D ARRAY**

In [15]:
product_2d_array = product_array.reshape(2,5)

In [16]:
product_array

array(['fruit', 'vegeteable', 'cereal', 'dairy', 'eggs', 'snacks',
       'beverages', 'coffee', 'tea', 'spices'], dtype='<U10')

In [17]:
product_2d_array[0,4]

np.str_('eggs')

In [18]:
product_2d_array

array([['fruit', 'vegeteable', 'cereal', 'dairy', 'eggs'],
       ['snacks', 'beverages', 'coffee', 'tea', 'spices']], dtype='<U10')

In [19]:
product_2d_array[0:, :2]

array([['fruit', 'vegeteable'],
       ['snacks', 'beverages']], dtype='<U10')

In [20]:
product_2d_array[1:, 2:]

array([['coffee', 'tea', 'spices']], dtype='<U10')

In [21]:
product_2d_array[:, 1:4]

array([['vegeteable', 'cereal', 'dairy'],
       ['beverages', 'coffee', 'tea']], dtype='<U10')

In [22]:
new_2d_array = np.arange(11,23)
new_2d_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [23]:
new_2d_array = np.arange(11,23).reshape(3,4)
new_2d_array

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [24]:
new_2d_array[1:, 1:]

array([[16, 17, 18],
       [20, 21, 22]])

In [25]:
new_2d_array[:2, 1:3]

array([[12, 13],
       [16, 17]])

In [26]:
new_2d_array[:, 2:]

array([[13, 14],
       [17, 18],
       [21, 22]])

In [27]:
new_2d_array[:, 1:2]

array([[12],
       [16],
       [20]])

## **_QUESTIONS_**
1. Create and inspect an 1d array [12,24,36,48,60], tell total no of elements.
2. Create two 1d array using 8 zeros and 8 ones respectively.
3. Create a 4:3 numpy array filled with zeros (show rows and columns).
4. Convert a python list[45,67,89,90,55] into numpy array .
5. Create a array of 6 random decimal vals, b/w 0:1
6. 10 random integer (limit: 50-100)
7. Create 8 random no. using normal distribution (mean = 100, sd = 10)
8. Create 2:3 array with 6 zeros and 3:2 array with 6 ones and random integer array of 4 vals (1-20)
9. Create an array of 5 student id using random int(1000-9990) & an array of 5 addendance % using random decimal & array of 5 test score with (mean 70 and std dev=8)

In [52]:
# QUESTION 1
arr_1d = np.array([12, 24, 36, 48, 60])
print(arr_1d)
print('size = ',arr_1d.size)

[12 24 36 48 60]
size =  5


In [57]:
# QUESTION 2
arr_zeros = np.zeros((1,8), dtype=int)
print("Zeros 1d array = ", arr_zeros)
arr_ones = np.ones((1,8), dtype=int)
print("Ones 1d array = ", arr_ones)

Zeros 1d array =  [[0 0 0 0 0 0 0 0]]
Ones 1d array =  [[1 1 1 1 1 1 1 1]]


In [64]:
# QUESTION 3
arr_2d = np.zeros((4, 3), dtype=int)
print(arr_2d)
print("DIMENTION = ", arr_2d.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
DIMENTION =  (4, 3)


In [66]:
# QUESTION 4
lst = [45,67,89,90,55]
np_arr = np.array(lst)
np_arr

array([45, 67, 89, 90, 55])

In [83]:
# QUESTION 5
rng = np.random.default_rng()
rand_arr = rng.random(6).round(2)
rand_arr

array([0.64, 0.67, 0.62, 0.88, 0.18, 0.36])

In [84]:
# QUESTION 6
rand = rng.integers(low = 50, high = 100, size = 10)
rand

array([64, 70, 80, 50, 66, 51, 74, 66, 58, 65])

In [85]:
# QUESTION 7
rand_normal = np.random.normal(100, 10, 8)
rand_normal

array([ 91.986548  , 101.43760622, 114.92645491,  99.66635958,
       104.8431323 ,  94.99357325, 103.7380718 ,  90.52115173])

In [86]:
# QUESTION 8
rand_01 = np.zeros((2,3), dtype=int)
rand_02 = np.ones((3,2), dtype=int)
rand_03 = rng.integers(low=1, high=20, size=4)
print(rand_01)
print(rand_02)
print(rand_03)

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]
[ 9  1 18  6]


In [92]:
# QUESTION 9
# numpy.random.randint(low, high=None, size=None, dtype=int)
std_id = np.random.randint(low=1000, high=9990, size=5, dtype=int)
print("Student id: ", std_id)

attendance = np.random.rand(5) * 100
print("Attendance in %: ", np.round(attendance, 2))

test_scr = np.random.normal(70, 8, 5)
print("Test Score: ", test_scr)

Student id:  [8037 8959 8406 7177 8698]
Attendance in %:  [56.17 45.57 93.47 82.74 63.96]
Test Score:  [67.38166837 63.29660686 60.41951901 75.33898982 73.14159573]
