# Class 10
## Date: 04-04-2026

## **ARRAY - _Operation_**

In [79]:
import numpy as np

In [24]:
rng = np.random.default_rng(243)   #here 243 is seeding val, Using a seed ensures that every time I run this code, I get the exact same "random" numbers.
inv = rng.integers(0,100,10)
inv

array([90, 47, 65, 87, 96, 82, 55, 92, 84, 28])

In [16]:
inv+2

array([92, 49, 67, 89, 98, 84, 57, 94, 86, 30])

In [17]:
price1 = (rng.random(11)*20).round(2)
price = (rng.random(10)*20).round(2)
print(price1)
print(price)

[ 6.56  8.08 15.23 14.74 14.25  0.85 18.61 13.83 18.91 12.23  3.72]
[13.89  9.3  14.1   6.52  2.97  7.    4.76  8.75  5.94  6.74]


In [18]:
rng.random(11)

array([0.41654194, 0.31932226, 0.92074616, 0.13141091, 0.91887115,
       0.46387141, 0.9471568 , 0.71211451, 0.63017694, 0.87215205,
       0.90014251])

In [19]:
inv*price

array([1250.1 ,  437.1 ,  916.5 ,  567.24,  285.12,  574.  ,  261.8 ,
        805.  ,  498.96,  188.72])

In [22]:
price2 = (rng.random(10)*5).round(0)
price2

array([2., 4., 1., 1., 4., 1., 4., 4., 4., 0.])

In [23]:
np.unique(price)

array([ 2.97,  4.76,  5.94,  6.52,  6.74,  7.  ,  8.75,  9.3 , 13.89,
       14.1 ])

## **_Filtering_**

In [38]:
sales = rng.integers(100,1000,10)

In [39]:
sales>500

array([ True, False,  True,  True,  True,  True,  True,  True, False,
       False])

In [40]:
sales

array([702, 267, 965, 724, 672, 518, 783, 734, 276, 393])

In [41]:
sales[sales>500]

array([702, 965, 724, 672, 518, 783, 734])

In [42]:
sales[sales%2 == 0]

array([702, 724, 672, 518, 734, 276])

In [46]:
sales[sales%2 != 0]

array([267, 965, 783, 393])

In [43]:
sales%2 == 0

array([ True, False, False,  True,  True,  True, False,  True,  True,
       False])

In [45]:
rng1 = np.random.default_rng(101)
sales1 = rng1.integers(100,1000,10)
sales1

array([379, 949, 726, 423, 221, 806, 458, 632, 657, 364])

In [51]:
x = rng.integers(0,100,10).reshape(2,5)
x[x>25]

array([90, 87, 54, 90, 86, 28, 56, 76, 33])

In [66]:
x

array([[90, 87, 54, 90, 86],
       [28, 56, 12, 76, 33]])

In [67]:
# x[(x<12) and (x<90)] - and : will throw error here as it is used for boolean operation
x[(x>12) & (x<90)] # &: for bitwise operation

array([87, 54, 86, 28, 56, 76, 33])

In [68]:
x[(x<54) | (x==90)]

array([90, 90, 28, 12, 33])

In [91]:
inventory = [1, 102, 10, 0, 0, 12]
products = ['oil', 'spices', 'seeds', 'dairy', 'eggs', 'fruits']
inventory_array = np.array(inventory)
products_array = np.array(products)

In [86]:
inventory_array

array([  0, 102,  10,   1,   0,  12])

In [87]:
products_array

array(['oil', 'spices', 'seeds', 'dairy', 'eggs', 'fruits'], dtype='<U6')

In [88]:
products_array[inventory_array==0]

array(['oil', 'eggs'], dtype='<U6')

In [92]:
products_array[inventory_array==0]

array(['dairy', 'eggs'], dtype='<U6')

In [93]:
product_array

array(['oil', 'spices', 'seeds', 'dairy', 'eggs', 'fruits'], dtype='<U6')

In [94]:
inventory_array

array([  1, 102,  10,   0,   0,  12])

## _WHERE fxn_
**np.where(condition,[x,y])**

In [98]:
np.where(inventory_array>0)

(array([0, 1, 2, 5]),)

In [99]:
np.where(inventory_array>0,'product in stock', 'product out of stock')

array(['product in stock', 'product in stock', 'product in stock',
       'product out of stock', 'product out of stock', 'product in stock'],
      dtype='<U20')

In [101]:
np.where(inventory_array<=0, products_array, 'in stock')

array(['in stock', 'in stock', 'in stock', 'dairy', 'eggs', 'in stock'],
      dtype='<U8')

In [103]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [108]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

In [110]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        

In [115]:
np.where(my_array == 9, my_array, np.where(my_array%2 == 0, 'even', 'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

In [130]:
sales_array = rng.integers(0,100,10).reshape(2,5)
sales_array.sum()

np.int64(609)

In [127]:
sales_array.mean()

np.float64(46.8)

In [128]:
sales_array.max()

np.int64(79)

In [129]:
sales_array.min()

np.int64(8)

In [132]:
sales_array

array([[79, 90, 83, 94, 71],
       [38, 22, 76, 36, 20]])

In [133]:
sales_array.sort()

In [134]:
sales_array

array([[71, 79, 83, 90, 94],
       [20, 22, 36, 38, 76]])

**_When you sort with axis=0, you are sorting down the columns._**

In [141]:
sales_array.sort(axis=0)

In [142]:
sales_array

array([[20, 22, 36, 38, 76],
       [71, 79, 83, 90, 94]])

In [143]:
sales_array.sum(axis=0)

array([ 91, 101, 119, 128, 170])

In [144]:
sales_array.sum(axis=1)

array([192, 417])

### **QUESTIONS**
1. Make a list comprehension where range is 0-100, element 10, convert it into array of 5 by 2. Get dim, shape, no of element, data type.
2. Make 3 arrays, in 3 different methods/fxns, 5 by 2 , range: 10-100
3. Seeding 2026, create 9 random number - 3x3 matrix,. print 1st 2 rows, then 1st column, then 2nd element of 3rd row

In [170]:
# QUESTION 1
lst = [i for i in range(0, 100, 10)]
arr = np.array(lst).reshape(5,2)
print('array: \n', arr)
print('dimention:', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('data type: ', arr.dtype)

array: 
 [[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]
dimention: 2
shape:  (5, 2)
size:  10
data type:  int64


In [203]:
# QUESTION 2
lst1 = [i for i in range(10, 101, 10)]
arr1 = np.array(lst1).reshape(5,2)

arr2 = np.arange(10,101,10).reshape(5,2)

lst2 = list(range(10, 101, 10))
arr3 = np.array(lst2).reshape(5,2)

arr4 = np.linspace(10,100,10).reshape(5,2)

print('array 1:\n', arr1)
print('array 2:\n', arr2)
print('array 3:\n', arr3)
print('array 4:\n', arr4)

array 1:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
array 2:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
array 3:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
array 4:
 [[ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]
 [ 70.  80.]
 [ 90. 100.]]


In [236]:
# QUESTION 3
x = np.random.default_rng(2026)
arr5 = x.random(9).reshape(3,3)
print('ARRAY\n',arr5)

print('\nARRAY 1st 2 rows\n',arr5[:2,])
print('\nARRAY 1st column\n',arr5[:, 0])
print('\nARRAY 2nd element of 3rd row\n',arr5[2,1])

ARRAY
 [[0.17893481 0.63991317 0.4672684 ]
 [0.37050053 0.35491733 0.79051825]
 [0.90514384 0.17735319 0.6527848 ]]

ARRAY 1st 2 rows
 [[0.17893481 0.63991317 0.4672684 ]
 [0.37050053 0.35491733 0.79051825]]

ARRAY 1st column
 [0.17893481 0.37050053 0.90514384]

ARRAY 2nd element of 3rd row
 0.17735319182304865
