# Class 8
## Date: 14/03/2026

# **NUMPY**

In [5]:
import numpy as np
list_1 = [0, 1, 10 ,20]
first_array = np.array([list_1])

In [6]:
first_array

array([[ 0,  1, 10, 20]])

In [7]:
array_2d = np.array([range(5) , range(5)])
array_2d                    

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
all_one_array = np.ones((3,2), dtype = int)
all_one_array

array([[1, 1],
       [1, 1],
       [1, 1]])

In [9]:
all_one = np.ones((4,2), dtype = "int")
all_one

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [10]:
all_zero = np.zeros((3,2))
all_zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
rng = np.random.default_rng(0)
random_array = rng.random(10).round(2)
random_array

array([0.64, 0.27, 0.04, 0.02, 0.81, 0.91, 0.61, 0.73, 0.54, 0.94])

default.rng [default random number genrator] makes sure that the same random numbers are generated for differnt users. 
SEEDING: it is a method to give a starting point for generating random numbers which will give same result for all users.

In [12]:
r_Int = rng.integers(low = 10, high = 100, size = 10) #to genrate random integer
r_Int

array([34, 83, 70, 10, 45, 87, 59, 13, 78, 75])

In [13]:
rints = rng.integers (0, 100, 10)
rints

array([84, 17,  8, 86,  2, 54,  8, 29, 48, 42])

In [14]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
np.linspace(0, 100, 11) # for creating an array of evenly spaced numbers over a specified interval

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

np.linspace divides data into equal parts, arnage give a range of numbers at defined intervals between two numbers. <matplot.lib> is a visualisation lib for python.             
int32, int64 etc helps us set sizes for data. This is usefull for Ml and LLM so that the data is store concisely and frees up the storage.

In [16]:
multidimension = np.array([[10,20,30],[20,30,40]],dtype="int8")
multidimension.ndim

2

In [17]:
multidimension.shape

(2, 3)

In [18]:
multidimension.itemsize

1

In [19]:
multidimension.size

6

# _Questions_

Question 1: 

Make such a program that the if the mrp and discount are given as argumnet, the programm retures the final amount to be payed.

Question 2:

A list is passed in and the programm returns the lowest number in the list.

Question 3:

A programm which should give the count of the vowels in a word.

Question 4:

A programm whuch gives the all teh divisor of the number.

Question 5:

A programm which calculates the tax.

0 - 25,00,000 = 0

25,00,001 - 50,00,000 = 5%

+50,00,001 = 10%


In [147]:

#  Answer 1  # 

def finalPayment (mrp, discount):
    return mrp - (discount*mrp/100)

price_1 = finalPayment(1000, 20)
price_2 = finalPayment(500,5)
print (price_1)
print (price_2)

800.0
475.0


In [141]:

#  Answer 2  # 

def lowestValue (numbers):
    for i in numbers:
        if i > i:
            print(i)

In [142]:
numberList = [1,2,3,4,5,6]
lowestValue(numberList)

In [153]:
def lowestValue (i):
    minimum = i[0]
    for n in i:
        if n < minimum:
           minimum = n
    return minimum

In [154]:
lowestValue(numberList)

1

In [155]:

# Answer 3 #


def vowelCount (string):
    word = input("Enter a Word:")
    count = 0
    for ch in string.lower():
        count += 1
    return "Vowel Count", count

In [156]:
name = "aeu"
vowelCount(name)

Enter a Word: agekbkc


('Vowel Count', 3)

In [ ]:
# Answer 4 #



In [131]:

# Answer 5 #

def calculateTax(income):
    if income <= 2500000:
        print("No TAX")
        return income  
    elif income <= 5000000: 
        tax = (5 * income) / 100
        return tax
    else: 
        tax = (10 * income) / 100
        return tax

In [133]:
calculateTax(3000000)

150000.0

In [134]:
calculateTax(2300)

No TAX


2300