# Class 10
## Date: 04-04-2026
### **_SHREYIT SINHA (M2024BSASS027)_**

### Package Imports

In [41]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [42]:
my_list = [x * 10 for x in range(1, 11)]

In [43]:
arr = np.array(my_list).reshape(2, 5)
arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [44]:
arr.shape

(2, 5)

In [45]:
arr.size

10

In [46]:
arr.dtype

dtype('int64')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [75]:
lst = [i for i in range(10, 101, 10)]
arr_1 = np.array(lst).reshape(5, 2)
arr_1

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [48]:
rng = np.random.default_rng(2022)
random_array = rng.random(9).reshape(3, 3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second element of the third row.

Thanks!


In [51]:
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [52]:
random_array[:2,:]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [53]:
random_array[0:3,0]

array([0.24742606, 0.06066207, 0.1108689 ])

In [55]:
random_array[2,1]

np.float64(0.04305584439252108)

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [62]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
shipping_fee = 5
total = prices + shipping_fee
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [71]:
discount_pct = random_array.reshape(-1)[0:6]
discount_pct

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778])

In [72]:
pct_owed = 1 - discount_pct
pct_owed

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [73]:
print('Final amt. owed =', total * pct_owed)

Final amt. owed = [ 8.27078756 10.87504916 10.67262487 98.6210889   3.38627605 13.4638738 ]


# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [77]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [89]:
price_mask = prices > 25
cola_mask = products == "cola" # Compares every product name to "cola" & this will create a boolean array that is True only for "cola".
print(price_mask)
print(cola_mask)

[False False False  True False  True]
[False False False False  True False]


In [87]:
fancy_feast_special = products[price_mask | cola_mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [88]:
shipping_cost = np.where(prices > 20, 0, 5)
shipping_cost

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [118]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices
print(np.sort(prices))


[ 4.99  5.99  6.99 22.49 49.99 99.99]


In [119]:
print('Mean:', np.mean(prices[-3:]))

Mean: 51.656666666666666


In [114]:
print('Min:', np.min(prices[-3:]))

Min: 4.99


In [115]:
print('Max:', np.max(prices[-3:]))

Max: 99.99


In [116]:
print('Median:', np.median(prices[-3:]))

Median: 49.99


In [117]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [121]:
unique_tiers = np.unique(price_tiers).size
unique_tiers

3

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [1]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

FileNotFoundError: [Errno 2] No such file or directory: 'retail_2016_2017.csv'

In [8]:
retail_df

,id,date,store_nbr,family,sales,onpromotion
0,1956943,2016-01-07,18,EGGS,177.00,0
1,1956944,2016-01-07,18,FROZEN FOODS,36.00,0
2,1956945,2016-01-07,18,GROCERY I,2291.06,6
3,1956946,2016-01-07,18,GROCERY II,16.00,0
4,1956947,2016-01-07,18,HARDWARE,2.00,0
...,...,...,...,...,...,...
995,1957938,2016-01-07,45,HOME AND KITCHEN I,83.00,0
996,1957939,2016-01-07,45,HOME AND KITCHEN II,97.00,1
997,1957940,2016-01-07,45,HOME APPLIANCES,1.00,0
998,1957941,2016-01-07,45,HOME CARE,510.00,1
