# Class 9
## Date: 23/03/2026
### **_SHREYIT SINHA (M2024BSASS027)_**

## **_QUESTIONS_**
1. Create and inspect an 1d array [12,24,36,48,60], tell total no of elements.
2. Create two 1d array using 8 zeros and 8 ones respectively.
3. Create a 4:3 numpy array filled with zeros (show rows and columns).
4. Convert a python list[45,67,89,90,55] into numpy array .
5. Create a array of 6 random decimal vals, b/w 0:1
6. 10 random integer (limit: 50-100)
7. Create 8 random no. using normal distribution (mean = 100, sd = 10)
8. Create 2:3 array with 6 zeros and 3:2 array with 6 ones and random integer array of 4 vals (1-20)
9. Create an array of 5 student id using random int(1000-9990) & an array of 5 addendance % using random decimal & array of 5 test score with (mean 70 and std dev=8)

In [5]:
import numpy as np

In [6]:
# ANSWER 1
arr_1d = np.array([12, 24, 36, 48, 60])
print(arr_1d)
print('size = ',arr_1d.size)

[12 24 36 48 60]
size =  5


In [7]:
# ANSWER 2
arr_zeros = np.zeros((1,8), dtype=int)
print("Zeros 1d array = ", arr_zeros)
arr_ones = np.ones((1,8), dtype=int)
print("Ones 1d array = ", arr_ones)

Zeros 1d array =  [[0 0 0 0 0 0 0 0]]
Ones 1d array =  [[1 1 1 1 1 1 1 1]]


In [8]:
# ANSWER 3
arr_2d = np.zeros((4, 3), dtype=int)
print(arr_2d)
print("DIMENTION = ", arr_2d.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
DIMENTION =  (4, 3)


In [9]:
# ANSWER 4
lst = [45,67,89,90,55]
np_arr = np.array(lst)
np_arr

array([45, 67, 89, 90, 55])

In [10]:
# ANSWER 5
rng = np.random.default_rng()
rand_arr = rng.random(6).round(2)
rand_arr

array([0.8 , 0.83, 0.47, 0.75, 0.41, 0.3 ])

In [11]:
# ANSWER 6
rand = rng.integers(low = 50, high = 100, size = 10)
rand

array([66, 75, 65, 67, 85, 52, 50, 55, 86, 95])

In [12]:
# ANSWER 7
rand_normal = np.random.normal(100, 10, 8)
rand_normal

array([ 97.894759  , 110.81086232, 104.81396861,  84.21048898,
       103.00872016, 103.17564612,  92.80147963,  99.4837364 ])

In [19]:
# ANSWER 8
rand_01 = np.zeros((2,3), dtype=int)
rand_02 = np.ones((3,2), dtype=int)
rand_03 = rng.integers(low=1, high=20, size=4)
print("2:3 ARRAY with 6 zeros =\n", rand_01)
print("3:2 ARRAY with 6 ones =\n", rand_02)
print("random integer ARRAY of 4 vals (range: 1-20) =\n", rand_03)

2:3 ARRAY with 6 zeros =
 [[0 0 0]
 [0 0 0]]
3:2 ARRAY with 6 ones =
 [[1 1]
 [1 1]
 [1 1]]
random integer ARRAY of 4 vals (range: 1-20) =
 [12 17 16 14]


In [15]:
# ANSWER 9
# numpy.random.randint(low, high=None, size=None, dtype=int)
std_id = np.random.randint(low=1000, high=9990, size=5, dtype=int)
print("Student id: ", std_id)

attendance = np.random.rand(5) * 100
print("Attendance in %: ", np.round(attendance, 2))

test_scr = np.random.normal(70, 8, 5)
print("Test Score: ", test_scr)

Student id:  [3158 9420 5070 4551 9819]
Attendance in %:  [65.17  0.67 92.06 77.04 56.09]
Test Score:  [58.17714139 67.9050739  81.61835945 76.94375625 62.27592136]
